framework:
    cache:
        prefix_seed: app
        app: app.cache.queries
        pools:
            app.cache.queries:
                adapter: cache.adapter.apcu
                default_lifetime: 3600
