version: "3"

services:
    app:
        image: saphyel/php:latest
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www/html:rw,cached
            - app-cache:/var/www/html/var/cache/
            - ./var/log:/var/www/html/var/log:delegated
            - ./vendor:/var/www/html/vendor:delegated
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"
        environment:
            COMPOSER_ALLOW_SUPERUSER: 1
            COMPOSER_MEMORY_LIMIT: -1

    web:
        image: nginx:1.14-alpine
        ports:
            - 8080:80
        volumes:
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./:/var/www/html:ro
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"
        links:
            - app

volumes:
  app-cache: ~