monolog:
    handlers:
        main:
            type: stream
            path: "php://stdout"
            level: debug
            formatter: 'monolog.formatter.json'
            channels: ["!event", "!deprecation"]
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
