app_home_index:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    methods: GET
    defaults:
        template: 'home/index.html.twig'
        maxAge: 86400
        sharedAge: 86400
