services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Http\Steam:
        arguments: ['@steam.client', '%env(STEAM_API_KEY)%']

    App\Controller\SteamController:
        arguments: ['@app.cache.queries']