parameters:
    steam_api_key: "%env(STEAM_API_KEY)%"
    steam_api_url: "https://api.steampowered.com/"

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
